In [1]:
# importing pandas
import numpy as np
import pandas as pd

In [2]:
# creating series using list
a= pd.Series([1,2,3,4])
i=[4,3,2,1]
a=pd.Series([1,2,3,4],index=i)
print(a)

4    1
3    2
2    3
1    4
dtype: int64

In [3]:
# creating series using dictionary
d1={
    'a':12,
    'b':23
}
s=pd.Series(d1)
print(s)

a    12
b    23
dtype: int64

In [4]:
 # creating series using array
a= np.array([1,2,3,4])
x=pd.Series(a)
x

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
# Data frames using dictionary
d1={
    'name':['a','b','c','d'],
    'age':[1,2,3,4],
    'city':['x','y','z','w'],
    'sal':[5,6,7,8]    
}
ans=pd.DataFrame(d1)
ans

  name  age city  sal
0    a    1    x    5
1    b    2    y    6
2    c    3    z    7
3    d    4    w    8

In [6]:
# Data frames using list
# Default indexes 
l=[['a','b','c','d'],[1,2,3,4],['x','y','z','w'],[5,6,7,8]]
xyz=pd.DataFrame(l)
xyz

   0  1  2  3
0  a  b  c  d
1  1  2  3  4
2  x  y  z  w
3  5  6  7  8

In [7]:
# Creating own rows and columns
l=[['a','b','c','d'],[1,2,3,4],['x','y','z','w'],[5,6,7,8]]
c=['name','age','city','sal']
r=['1st','2nd','3rd','4th']
xyz=pd.DataFrame(l,index=r,columns=c)
xyz

    name age city sal
1st    a   b    c   d
2nd    1   2    3   4
3rd    x   y    z   w
4th    5   6    7   8

In [8]:
# Slicing of columns
xyz[['name','age']]

    name age
1st    a   b
2nd    1   2
3rd    x   y
4th    5   6

In [9]:
# Creating new columns
xyz['room']=[110,111,112,113]
xyz

    name age city sal  room
1st    a   b    c   d   110
2nd    1   2    3   4   111
3rd    x   y    z   w   112
4th    5   6    7   8   113

In [10]:
# deletion
xyz.drop('room',axis=1)

    name age city sal
1st    a   b    c   d
2nd    1   2    3   4
3rd    x   y    z   w
4th    5   6    7   8

In [11]:
xyz

    name age city sal  room
1st    a   b    c   d   110
2nd    1   2    3   4   111
3rd    x   y    z   w   112
4th    5   6    7   8   113

In [12]:
# deletion of rows
xyz.drop('1st',axis=0)

    name age city sal  room
2nd    1   2    3   4   111
3rd    x   y    z   w   112
4th    5   6    7   8   113

In [13]:
xyz

    name age city sal  room
1st    a   b    c   d   110
2nd    1   2    3   4   111
3rd    x   y    z   w   112
4th    5   6    7   8   113

In [14]:
# delete permanently
xyz.drop('room',axis=1,inplace=True)

In [15]:
xyz

    name age city sal
1st    a   b    c   d
2nd    1   2    3   4
3rd    x   y    z   w
4th    5   6    7   8

In [16]:
# Slicing of rows
xyz.loc['1st']

name    a
age     b
city    c
sal     d
Name: 1st, dtype: object

In [17]:
xyz.iloc[0]

name    a
age     b
city    c
sal     d
Name: 1st, dtype: object

In [18]:
dic1={
    'name': ['Ishan','Rohit','raj','xyz'],
    'mis': [660,345,181,139],
    'sec': ['a','b','n','d'],
    'branch':['x','y','z','w']
}
a=pd.DataFrame(dic1)
a

    name  mis sec branch
0  Ishan  660   a      x
1  Rohit  345   b      y
2    raj  181   n      z
3    xyz  139   d      w

In [19]:
# Both rows and column access
a.loc[1:3][['name','branch']]

    name branch
1  Rohit      y
2    raj      z
3    xyz      w

In [20]:
# conditional
a[(a['mis']>150) & (a['branch']=='w')]

Empty DataFrame
Columns: [name, mis, sec, branch]
Index: []

In [21]:
# Null data
list=[[1,2,3,4,np.nan],
[1,np.nan,3,4,5],
[np.nan,2,3,np.nan,5],
[1,2,np.nan,np.nan,np.nan]]
c=['a','b','c','d','e']
df=pd.DataFrame(list,columns=c)
df

     a    b    c    d    e
0  1.0  2.0  3.0  4.0  NaN
1  1.0  NaN  3.0  4.0  5.0
2  NaN  2.0  3.0  NaN  5.0
3  1.0  2.0  NaN  NaN  NaN

In [22]:
# Nnumber of missing data per column
df.isna().sum()

a    1
b    1
c    1
d    2
e    2
dtype: int64

In [23]:
# filling missing data using one value
df.fillna(1000)

        a       b       c       d       e
0     1.0     2.0     3.0     4.0  1000.0
1     1.0  1000.0     3.0     4.0     5.0
2  1000.0     2.0     3.0  1000.0     5.0
3     1.0     2.0  1000.0  1000.0  1000.0

In [24]:
v={'a':200,'b':500,'c':300}
df.fillna(value=v)

       a      b      c    d    e
0    1.0    2.0    3.0  4.0  NaN
1    1.0  500.0    3.0  4.0  5.0
2  200.0    2.0    3.0  NaN  5.0
3    1.0    2.0  300.0  NaN  NaN

In [25]:
d1={
    'id1':[1,2,3,4],
    'name':['a','b','c','d'],
    'colid':[100,200,300,400]
}
d2={
    'id2':[1,2,3,4],
    'name':['a','b','c','d'],
    'colid':[100,200,500,600]
}
df1=pd.DataFrame(d1)
df2=pd.DataFrame(d2)

In [26]:
# Merging
pd.merge(df1,df2)

   id1 name  colid  id2
0    1    a    100    1
1    2    b    200    2

In [27]:
pd.merge(df1,df2,on='name')

   id1 name  colid_x  id2  colid_y
0    1    a      100    1      100
1    2    b      200    2      200
2    3    c      300    3      500
3    4    d      400    4      600

In [28]:
pd.concat([df1,df2])

   id1 name  colid  id2
0  1.0    a    100  NaN
1  2.0    b    200  NaN
2  3.0    c    300  NaN
3  4.0    d    400  NaN
0  NaN    a    100  1.0
1  NaN    b    200  2.0
2  NaN    c    500  3.0
3  NaN    d    600  4.0

In [29]:
pd.concat([df1,df2],axis=1)

   id1 name  colid  id2 name  colid
0    1    a    100    1    a    100
1    2    b    200    2    b    200
2    3    c    300    3    c    500
3    4    d    400    4    d    600

In [30]:
d1={
    'id1':[1,2,3,4],
    'name':['a','b','c','d'],
    'colid':[100,200,300,400]
}
d2={
    'id2':[1,2,3,4],
    'name':['a','b','c','d'],
    'colid':[100,300,500,600]
}
df1=pd.DataFrame(d1)
df2=pd.DataFrame(d2)

In [31]:
pd.merge(df1,df2,how='left')

   id1 name  colid  id2
0    1    a    100  1.0
1    2    b    200  NaN
2    3    c    300  NaN
3    4    d    400  NaN

In [32]:
pd.merge(df1,df2,how='right')

   id1 name  colid  id2
0  1.0    a    100    1
1  NaN    b    300    2
2  NaN    c    500    3
3  NaN    d    600    4

In [33]:
# JOINING DATA FRAMES
df1=pd.DataFrame({
    'Name':['raj','rohit','karan'],
})
df2=pd.DataFrame({
    'Score':[10,12,13,13]
})
df3=pd.DataFrame({
    'Rollno.':[101,102,103]
})
df4=df3.join(df1)
result=df4.join(df2)

In [34]:
result

   Rollno.   Name  Score
0      101    raj     10
1      102  rohit     12
2      103  karan     13

In [47]:
# Group by:
l=[['A','S1',100,10],['A','S2',200,25],['B','S1',120,15],['A','S2',150,20]]
c=['Category','Store','Sales','Quantity']
df=pd.DataFrame(l,columns=c)
df

  Category Store  Sales  Quantity
0        A    S1    100        10
1        A    S2    200        25
2        B    S1    120        15
3        A    S2    150        20

In [36]:
# Total sum
df.sum()[['Sales','Quantity']]

Sales       570
Quantity     70
dtype: object

In [37]:
# Category wise distribution
cat=df.groupby('Category')
for i,v in cat:
    print(i)
    print(v)
    print("-----------")

A
  Category Store  Sales  Quantity
0        A    S1    100        10
1        A    S2    200        25
3        A    S2    150        20
-----------
B
  Category Store  Sales  Quantity
2        B    S1    120        15
-----------

In [38]:
# Category wise sum:
cat.sum()[['Sales','Quantity']]

          Sales  Quantity
Category
A           450        55
B           120        15

In [39]:
# Grouping Multiple:
cat2=df.groupby(['Category','Store'])
for i,v in cat2:
    print(i)
    print(v)

('A', 'S1')
  Category Store  Sales  Quantity
0        A    S1    100        10
('A', 'S2')
  Category Store  Sales  Quantity
1        A    S2    200        25
3        A    S2    150        20
('B', 'S1')
  Category Store  Sales  Quantity
2        B    S1    120        15

In [40]:
# Aggregation Functions::
df['Sales'].mean()

np.float64(142.5)

In [41]:
df['Sales'].agg(['mean','median','std','count'])

mean      142.500000
median    135.000000
std        43.493295
count       4.000000
Name: Sales, dtype: float64

In [42]:
df.describe()

            Sales   Quantity
count    4.000000   4.000000
mean   142.500000  17.500000
std     43.493295   6.454972
min    100.000000  10.000000
25%    115.000000  13.750000
50%    135.000000  17.500000
75%    162.500000  21.250000
max    200.000000  25.000000

In [49]:
# write a function to square a sqaure the values of sales:
def sq(n):
    return n*n
df['Sales']=sq(df['Sales'])
df

  Category Store       Sales  Quantity
0        A    S1   100000000        10
1        A    S2  1600000000        25
2        B    S1   207360000        15
3        A    S2   506250000        20